# Generated by Django 4.1.4 on 2022-12-23 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("bio", models.TextField(default="")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Others", "Others"),
                            ("Male", "Male"),
                            ("Female", "Female"),
                        ],
                        default="None",
                        max_length=10,
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True, default="/profile_default.png", upload_to="picture"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=500)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
